stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo "Building the project"
  pool:
    name: Pool1

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: echo "Running tests"
  pool:
    name: Pool2

