stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo "Building the project"
  pool:
     vmImage: ubuntu-latest

- stage: Test
  dependsOn: Build
  jobs:
  - job: Test
    steps:
    - script: echo "Running tests"
  pool:
     vmImage: ubuntu-latest

